#!/bin/bash
# Helper script to download WordPress export from existing site

echo "WordPress Content Export Helper"
echo "================================"
echo ""
echo "This script helps you export content from your existing WordPress site."
echo ""
echo "Manual Steps:"
echo "1. Open https://leftlane.io/wp-admin in your browser"
echo "2. Go to Tools → Export"
echo "3. Select 'All content'"
echo "4. Click 'Download Export File'"
echo "5. Save the file"
echo ""
echo "Then run this command:"
echo ""
echo "  cp ~/Downloads/[your-export-file].xml ./content/export.xml"
echo ""
echo "Or if you have WP-CLI installed on your server:"
echo ""
echo "  ssh your-server 'cd /path/to/wordpress && wp export' > ./content/export.xml"
echo ""
echo "After copying the file, commit and push:"
echo ""
echo "  git add content/export.xml"
echo "  git commit -m 'Add content export from leftlane.io'"
echo "  git push"
echo ""

